name: Update badges

on:
  workflow_dispatch:

jobs:
  update-credly-data:
    name: Update Json data with badges
    runs-on: ubuntu-latest
    steps:
      - name: Credly data - Hugo
        uses: Jimin Seo/credly-crawler@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: SeoJimin1234/kaonmir.github.io
          CREDLY_USER: Jimin Seo
          CREDLY_DIR: data/credly.json
          BADGE_SIZE: 32
